### ISSUE TITLE
Hearty thanks

### ISSUE THREAD

**Issue by lienguang0624** [mateus-amarante/master_thesis#1]
The subject of UAV payload swing angle control of load suspension has puzzled me for a long time. I sincerely thank you for your open source project, which has inspired me a lot

**Comment by mateus-amarante** [comment]
I'm very happy this work has been relevant to you. Thanks for your feedback @lienguang0624. Unfortunately, I only have it written in Portuguese. I was supposed to publish an article but I couldn't find time for it... Let me know if you need help with anything.

**Comment by lienguang0624** [comment]
I found some clerical errors in the formula (it may be my derivation error)
1.In formula 3.51，z_dot_dot = fx + bx*u1 +dz. Should it be the same as formula 2.39-3 z_dot_dot = fz + bz*u1 +dz
2.In formula 3.56,  s1_dot =(zd_dot-dot - z_dot_dot) + lambda_z*(zd - z). Should it be s1_dot =(zd_dot-dot - z_dot_dot) + lambda_z*(zd_dot - z_dot)

**Comment by lienguang0624** [comment]
I have another question about the derivation of the formula (3.61). According to your paper, first bring the z_dot_dot in the formula (3.51) into the formula (3.56), and then the formula (3.56) into the formula (3.58) and proceed After sorting to get the formula (3.61), I checked the calculation in this order, but I did not find dz (in formula 3.51) and lambda_z * (zd-z) (in formula 3.56) in formula (3.61), so please could you help me analyze what went wrong.
Need your help very much, thank you

**Comment by mateus-amarante** [comment]
> I found some clerical errors in the formula (it may be my derivation error)
> 1.In formula 3.51，z_dot_dot = fx + bx_u1 +dz. Should it be the same as formula 2.39-3 z_dot_dot = fz + bz_u1 +dz
> 2.In formula 3.56, s1_dot =(zd_dot-dot - z_dot_dot) + lambda_z*(zd - z). Should it be s1_dot =(zd_dot-dot - z_dot_dot) + lambda_z*(zd_dot - z_dot)

Nice catch! You are right about both equations!

**Comment by mateus-amarante** [comment]
> I have another question about the derivation of the formula (3.61). According to your paper, first bring the z_dot_dot in the formula (3.51) into the formula (3.56), and then the formula (3.56) into the formula (3.58) and proceed After sorting to get the formula (3.61), I checked the calculation in this order, but I did not find dz (in formula 3.51) and lambda_z * (zd-z) (in formula 3.56) in formula (3.61), so please could you help me analyze what went wrong.
> Need your help very much, thank you

The calculations are:

![Screenshot from 2021-01-11 07-00-36](https://user-images.githubusercontent.com/7409263/104167914-ef242a00-53db-11eb-9f9a-ce5d595f1b1f.png)

* You are right about (3.51), lambda_z * (zd-z) was supposed to be lambda_z * (zd_dot-z_dot). So, it must not appear in Eq. (3.61)
* At this stage, I wanted to define an equation for the input and I'm not considering `d_z` (yet), since it is unknown. `d_z` is considered on the definition of `eta_z` which is designed based on the bounds expected for the disturbances.

**Comment by mateus-amarante** [comment]
This [article](https://www.sciencedirect.com/science/article/abs/pii/S0019057814000512) was my main inspiration when I designed this controller. It might help you too!

**Comment by lienguang0624** [comment]
Thank you very much for your prompt reply. I have roughly understood the structure of your paper. Next, I want to repeat your simulation work, but I encountered some difficulties while reading your source code.
The return value of the rL_fun(t) function in the waypoint_shaped_flat_trajectory.m file is a matrix of 2801*21. I know that 2801 represents the time node, but how is this 21 obtained, and what does it specifically mean? (I can only analyze that rL_fun probably represents the position information of the suspanded load, but these are only three variables(xl,yl,zl))
The same problem is also true for yaw_fun(t). Why is the function running the result of 2801*3 if only one state variable is yaw?
Do you have any suggestions for reading your simulation program?
I am very sorry for taking up your precious time and looking forward to your reply.

**Comment by mateus-amarante** [comment]
> Thank you very much for your prompt reply. I have roughly understood the structure of your paper. Next, I want to repeat your simulation work, but I encountered some difficulties while reading your source code.
The return value of the rL_fun(t) function in the waypoint_shaped_flat_trajectory.m file is a matrix of 280121. I know that 2801 represents the time node, but how is this 21 obtained, and what does it specifically mean? (I can only analyze that rL_fun probably represents the position information of the suspanded load, but these are only three variables(xl,yl,zl))
The same problem is also true for yaw_fun(t). Why is the function running the result of 28013 if only one state variable is yaw?
Do you have any suggestions for reading your simulation program?
I am very sorry for taking up your precious time and looking forward to your reply.

Don't worry, I'm glad to help. Answering questions makes me learn more too.

I just want to ask you to create issues for new questions so we can organize the topics. I transferred your question to https://github.com/mateus-amarante/master_thesis/issues/3.

**Comment by lienguang0624** [comment]
Thank you for your unselfish answer. Wish you good health, a successful career and a happy day in the New Year
